server:
  port: 8091
logging:
  level: DEBUG
  config: classpath:log4j2.xml  
spring:
  profiles: 
    active: '@profileActive@'
  messages:
    basename: message/resource,message/lookup
    cache-seconds: ${args.messages.cache-seconds:5}
  datasource:
    url: ${args.datasource.url:jdbc:mysql://localhost:3306/yqyl_business?characterEncoding=utf-8&serverTimezone=GMT%2b8 }
    username: ${args.datasource.username:dev}
    password: ${args.datasource.password:!QAZ2wsx}
    driverClassName: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: select 1
    sqlScriptEncoding: utf-8
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

---
spring: 
  profiles: qa
args:
  messages: 
    cache-seconds: -1
  datasource: 
    url: jdbc:mysql://localhost:8099/yqyl_business?characterEncoding=utf-8&serverTimezone=GMT%2b8
  pos:
    shop: 400020000001
    terminal: 400000000002
    tsk: AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBB
    center:
      url: 172.16.29.200
      port: 11006
  sms:
    server: api.cloudfeng.com
    appid: jfl55g1s6vhcogxwvzhcbuhdurzi7ils
    appsec: 3ae9c724cc23142c7ece99cf9c0f5b6a6650
    batch: YQYL8888
---
spring: 
  profiles: prod
args:
  messages: 
    cache-seconds: -1
  datasource: 
    url: jdbc:mysql://mysql:3306/yqyl_business?characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: "!QAZ2wsx"
  pos:
    shop: 500000000001
    terminal: 500010000001
    tsk: AC297420EED4727130CCF2EADD23C188
    center:
      url: 172.16.40.198
      port: 11006
  sms:
    server: api.cloudfeng.com
    appid: jfl55g1s6vhcogxwvzhcbuhdurzi7ils
    appsec: 3ae9c724cc23142c7ece99cf9c0f5b6a6650
    batch: YQYL8888
---
spring: 
  profiles: dev-home
args:
  datasource: 
    url: jdbc:mysql://localhost:3306/yqyl_business?characterEncoding=utf-8&serverTimezone=GMT%2b8
  pos:
    shop: 400020000001
    terminal: 400000000002
    tsk: AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBB
    center:
      url: 172.16.29.200
      port: 11006
  sms:
    server: api.cloudfeng.com
    appid: jfl55g1s6vhcogxwvzhcbuhdurzi7ils
    appsec: 3ae9c724cc23142c7ece99cf9c0f5b6a6650
    batch: YQYL8888
     
---
spring: 
  profiles: dev-work
args:
  datasource: 
    url: jdbc:mysql://localhost:3306/yqyl_business?characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: devrw
    password: "!QAZ2wsx"
  pos:
    shop: 400020000001
    terminal: 400000000002
    tsk: AAAAAAAAAABBBBBBBBBBBBBBBBBBBBBB
    center:
      url: 172.16.29.200
      port: 11006
  sms:
    server: api.cloudfeng.com
    appid: jfl55g1s6vhcogxwvzhcbuhdurzi7ils
    appsec: 3ae9c724cc23142c7ece99cf9c0f5b6a6650
    batch: YQYL8888