package org.trinity.yqyl.common.message.lookup;

import org.trinity.message.ILookupMessage;

public enum City implements ILookupMessage<LookupType> {
    北京市_北京市(Province.北京市, "00"),

    天津市_天津市(Province.天津市, "00"),

    河北省_石家庄市(Province.河北省, "01"),
    河北省_唐山市(Province.河北省, "02"),
    河北省_秦皇岛市(Province.河北省, "03"),
    河北省_邯郸市(Province.河北省, "04"),
    河北省_邢台市(Province.河北省, "05"),
    河北省_保定市(Province.河北省, "06"),
    河北省_张家口市(Province.河北省, "07"),
    河北省_承德市(Province.河北省, "08"),
    河北省_沧州市(Province.河北省, "09"),
    河北省_廊坊市(Province.河北省, "10"),
    河北省_衡水市(Province.河北省, "11"),

    山西省_太原市(Province.山西省, "01"),
    山西省_大同市(Province.山西省, "02"),
    山西省_阳泉市(Province.山西省, "03"),
    山西省_长治市(Province.山西省, "04"),
    山西省_晋城市(Province.山西省, "05"),
    山西省_朔州市(Province.山西省, "06"),
    山西省_晋中市(Province.山西省, "07"),
    山西省_运城市(Province.山西省, "08"),
    山西省_忻州市(Province.山西省, "09"),
    山西省_临汾市(Province.山西省, "10"),
    山西省_吕梁市(Province.山西省, "11"),

    内蒙古自治区_呼和浩特市(Province.内蒙古自治区, "01"),
    内蒙古自治区_包头市(Province.内蒙古自治区, "02"),
    内蒙古自治区_乌海市(Province.内蒙古自治区, "03"),
    内蒙古自治区_赤峰市(Province.内蒙古自治区, "04"),
    内蒙古自治区_通辽市(Province.内蒙古自治区, "05"),
    内蒙古自治区_鄂尔多斯市(Province.内蒙古自治区, "06"),
    内蒙古自治区_呼伦贝尔市(Province.内蒙古自治区, "07"),
    内蒙古自治区_巴彦淖尔市(Province.内蒙古自治区, "08"),
    内蒙古自治区_乌兰察布市(Province.内蒙古自治区, "09"),
    内蒙古自治区_兴安盟(Province.内蒙古自治区, "22"),
    内蒙古自治区_锡林郭勒盟(Province.内蒙古自治区, "25"),
    内蒙古自治区_阿拉善盟(Province.内蒙古自治区, "29"),

    辽宁省_沈阳市(Province.辽宁省, "01"),
    辽宁省_大连市(Province.辽宁省, "02"),
    辽宁省_鞍山市(Province.辽宁省, "03"),
    辽宁省_抚顺市(Province.辽宁省, "04"),
    辽宁省_本溪市(Province.辽宁省, "05"),
    辽宁省_丹东市(Province.辽宁省, "06"),
    辽宁省_锦州市(Province.辽宁省, "07"),
    辽宁省_营口市(Province.辽宁省, "08"),
    辽宁省_阜新市(Province.辽宁省, "09"),
    辽宁省_辽阳市(Province.辽宁省, "10"),
    辽宁省_盘锦市(Province.辽宁省, "11"),
    辽宁省_铁岭市(Province.辽宁省, "12"),
    辽宁省_朝阳市(Province.辽宁省, "13"),
    辽宁省_葫芦岛市(Province.辽宁省, "14"),

    吉林省_长春市(Province.吉林省, "01"),
    吉林省_吉林市(Province.吉林省, "02"),
    吉林省_四平市(Province.吉林省, "03"),
    吉林省_辽源市(Province.吉林省, "04"),
    吉林省_通化市(Province.吉林省, "05"),
    吉林省_白山市(Province.吉林省, "06"),
    吉林省_松原市(Province.吉林省, "07"),
    吉林省_白城市(Province.吉林省, "08"),
    吉林省_延边朝鲜族自治州(Province.吉林省, "24"),

    黑龙江省_哈尔滨市(Province.黑龙江省, "01"),
    黑龙江省_齐齐哈尔市(Province.黑龙江省, "02"),
    黑龙江省_鸡西市(Province.黑龙江省, "03"),
    黑龙江省_鹤岗市(Province.黑龙江省, "04"),
    黑龙江省_双鸭山市(Province.黑龙江省, "05"),
    黑龙江省_大庆市(Province.黑龙江省, "06"),
    黑龙江省_伊春市(Province.黑龙江省, "07"),
    黑龙江省_佳木斯市(Province.黑龙江省, "08"),
    黑龙江省_七台河市(Province.黑龙江省, "09"),
    黑龙江省_牡丹江市(Province.黑龙江省, "10"),
    黑龙江省_黑河市(Province.黑龙江省, "11"),
    黑龙江省_绥化市(Province.黑龙江省, "12"),
    黑龙江省_大兴安岭地区(Province.黑龙江省, "27"),

    上海市_上海市(Province.上海市, "00"),

    江苏省_南京市(Province.江苏省, "01"),
    江苏省_无锡市(Province.江苏省, "02"),
    江苏省_徐州市(Province.江苏省, "03"),
    江苏省_常州市(Province.江苏省, "04"),
    江苏省_苏州市(Province.江苏省, "05"),
    江苏省_南通市(Province.江苏省, "06"),
    江苏省_连云港市(Province.江苏省, "07"),
    江苏省_淮安市(Province.江苏省, "08"),
    江苏省_盐城市(Province.江苏省, "09"),
    江苏省_扬州市(Province.江苏省, "10"),
    江苏省_镇江市(Province.江苏省, "11"),
    江苏省_泰州市(Province.江苏省, "12"),
    江苏省_宿迁市(Province.江苏省, "13"),

    浙江省_杭州市(Province.浙江省, "01"),
    浙江省_宁波市(Province.浙江省, "02"),
    浙江省_温州市(Province.浙江省, "03"),
    浙江省_嘉兴市(Province.浙江省, "04"),
    浙江省_湖州市(Province.浙江省, "05"),
    浙江省_绍兴市(Province.浙江省, "06"),
    浙江省_金华市(Province.浙江省, "07"),
    浙江省_衢州市(Province.浙江省, "08"),
    浙江省_舟山市(Province.浙江省, "09"),
    浙江省_台州市(Province.浙江省, "10"),
    浙江省_丽水市(Province.浙江省, "11"),

    安徽省_合肥市(Province.安徽省, "01"),
    安徽省_芜湖市(Province.安徽省, "02"),
    安徽省_蚌埠市(Province.安徽省, "03"),
    安徽省_淮南市(Province.安徽省, "04"),
    安徽省_马鞍山市(Province.安徽省, "05"),
    安徽省_淮北市(Province.安徽省, "06"),
    安徽省_铜陵市(Province.安徽省, "07"),
    安徽省_安庆市(Province.安徽省, "08"),
    安徽省_黄山市(Province.安徽省, "10"),
    安徽省_滁州市(Province.安徽省, "11"),
    安徽省_阜阳市(Province.安徽省, "12"),
    安徽省_宿州市(Province.安徽省, "13"),
    安徽省_巢湖市(Province.安徽省, "14"),
    安徽省_六安市(Province.安徽省, "15"),
    安徽省_亳州市(Province.安徽省, "16"),
    安徽省_池州市(Province.安徽省, "17"),
    安徽省_宣城市(Province.安徽省, "18"),

    福建省_福州市(Province.福建省, "01"),
    福建省_厦门市(Province.福建省, "02"),
    福建省_莆田市(Province.福建省, "03"),
    福建省_三明市(Province.福建省, "04"),
    福建省_泉州市(Province.福建省, "05"),
    福建省_漳州市(Province.福建省, "06"),
    福建省_南平市(Province.福建省, "07"),
    福建省_龙岩市(Province.福建省, "08"),
    福建省_宁德市(Province.福建省, "09"),

    江西省_南昌市(Province.江西省, "01"),
    江西省_景德镇市(Province.江西省, "02"),
    江西省_萍乡市(Province.江西省, "03"),
    江西省_九江市(Province.江西省, "04"),
    江西省_新余市(Province.江西省, "05"),
    江西省_鹰潭市(Province.江西省, "06"),
    江西省_赣州市(Province.江西省, "07"),
    江西省_吉安市(Province.江西省, "08"),
    江西省_宜春市(Province.江西省, "09"),
    江西省_抚州市(Province.江西省, "10"),
    江西省_上饶市(Province.江西省, "11"),

    山东省_济南市(Province.山东省, "01"),
    山东省_青岛市(Province.山东省, "02"),
    山东省_淄博市(Province.山东省, "03"),
    山东省_枣庄市(Province.山东省, "04"),
    山东省_东营市(Province.山东省, "05"),
    山东省_烟台市(Province.山东省, "06"),
    山东省_潍坊市(Province.山东省, "07"),
    山东省_济宁市(Province.山东省, "08"),
    山东省_泰安市(Province.山东省, "09"),
    山东省_威海市(Province.山东省, "10"),
    山东省_日照市(Province.山东省, "11"),
    山东省_莱芜市(Province.山东省, "12"),
    山东省_临沂市(Province.山东省, "13"),
    山东省_德州市(Province.山东省, "14"),
    山东省_聊城市(Province.山东省, "15"),
    山东省_滨州市(Province.山东省, "16"),
    山东省_菏泽市(Province.山东省, "17"),

    河南省_郑州市(Province.河南省, "01"),
    河南省_开封市(Province.河南省, "02"),
    河南省_洛阳市(Province.河南省, "03"),
    河南省_平顶山市(Province.河南省, "04"),
    河南省_安阳市(Province.河南省, "05"),
    河南省_鹤壁市(Province.河南省, "06"),
    河南省_新乡市(Province.河南省, "07"),
    河南省_焦作市(Province.河南省, "08"),
    河南省_濮阳市(Province.河南省, "09"),
    河南省_许昌市(Province.河南省, "10"),
    河南省_漯河市(Province.河南省, "11"),
    河南省_三门峡市(Province.河南省, "12"),
    河南省_南阳市(Province.河南省, "13"),
    河南省_商丘市(Province.河南省, "14"),
    河南省_信阳市(Province.河南省, "15"),
    河南省_周口市(Province.河南省, "16"),
    河南省_驻马店市(Province.河南省, "17"),

    湖北省_武汉市(Province.湖北省, "01"),
    湖北省_黄石市(Province.湖北省, "02"),
    湖北省_十堰市(Province.湖北省, "03"),
    湖北省_宜昌市(Province.湖北省, "05"),
    湖北省_襄樊市(Province.湖北省, "06"),
    湖北省_鄂州市(Province.湖北省, "07"),
    湖北省_荆门市(Province.湖北省, "08"),
    湖北省_孝感市(Province.湖北省, "09"),
    湖北省_荆州市(Province.湖北省, "10"),
    湖北省_黄冈市(Province.湖北省, "11"),
    湖北省_咸宁市(Province.湖北省, "12"),
    湖北省_随州市(Province.湖北省, "13"),
    湖北省_恩施土家族苗族自治州(Province.湖北省, "28"),

    湖南省_长沙市(Province.湖南省, "01"),
    湖南省_株洲市(Province.湖南省, "02"),
    湖南省_湘潭市(Province.湖南省, "03"),
    湖南省_衡阳市(Province.湖南省, "04"),
    湖南省_邵阳市(Province.湖南省, "05"),
    湖南省_岳阳市(Province.湖南省, "06"),
    湖南省_常德市(Province.湖南省, "07"),
    湖南省_张家界市(Province.湖南省, "08"),
    湖南省_益阳市(Province.湖南省, "09"),
    湖南省_郴州市(Province.湖南省, "10"),
    湖南省_永州市(Province.湖南省, "11"),
    湖南省_怀化市(Province.湖南省, "12"),
    湖南省_娄底市(Province.湖南省, "13"),
    湖南省_湘西土家族苗族自治州(Province.湖南省, "31"),

    广东省_广州市(Province.广东省, "01"),
    广东省_韶关市(Province.广东省, "02"),
    广东省_深圳市(Province.广东省, "03"),
    广东省_珠海市(Province.广东省, "04"),
    广东省_汕头市(Province.广东省, "05"),
    广东省_佛山市(Province.广东省, "06"),
    广东省_江门市(Province.广东省, "07"),
    广东省_湛江市(Province.广东省, "08"),
    广东省_茂名市(Province.广东省, "09"),
    广东省_肇庆市(Province.广东省, "12"),
    广东省_惠州市(Province.广东省, "13"),
    广东省_梅州市(Province.广东省, "14"),
    广东省_汕尾市(Province.广东省, "15"),
    广东省_河源市(Province.广东省, "16"),
    广东省_阳江市(Province.广东省, "17"),
    广东省_清远市(Province.广东省, "18"),
    广东省_东莞市(Province.广东省, "19"),
    广东省_中山市(Province.广东省, "20"),
    广东省_潮州市(Province.广东省, "51"),
    广东省_揭阳市(Province.广东省, "52"),
    广东省_云浮市(Province.广东省, "53"),

    广西壮族自治区_南宁市(Province.广西壮族自治区, "01"),
    广西壮族自治区_柳州市(Province.广西壮族自治区, "02"),
    广西壮族自治区_桂林市(Province.广西壮族自治区, "03"),
    广西壮族自治区_梧州市(Province.广西壮族自治区, "04"),
    广西壮族自治区_北海市(Province.广西壮族自治区, "05"),
    广西壮族自治区_防城港市(Province.广西壮族自治区, "06"),
    广西壮族自治区_钦州市(Province.广西壮族自治区, "07"),
    广西壮族自治区_贵港市(Province.广西壮族自治区, "08"),
    广西壮族自治区_玉林市(Province.广西壮族自治区, "09"),
    广西壮族自治区_百色市(Province.广西壮族自治区, "10"),
    广西壮族自治区_贺州市(Province.广西壮族自治区, "11"),
    广西壮族自治区_河池市(Province.广西壮族自治区, "12"),
    广西壮族自治区_来宾市(Province.广西壮族自治区, "13"),
    广西壮族自治区_崇左市(Province.广西壮族自治区, "14"),

    海南省_海口市(Province.海南省, "01"),
    海南省_三亚市(Province.海南省, "02"),

    重庆市_重庆市(Province.重庆市, "00"),

    四川省_成都市(Province.四川省, "01"),
    四川省_自贡市(Province.四川省, "03"),
    四川省_攀枝花市(Province.四川省, "04"),
    四川省_泸州市(Province.四川省, "05"),
    四川省_德阳市(Province.四川省, "06"),
    四川省_绵阳市(Province.四川省, "07"),
    四川省_广元市(Province.四川省, "08"),
    四川省_遂宁市(Province.四川省, "09"),
    四川省_内江市(Province.四川省, "10"),
    四川省_乐山市(Province.四川省, "11"),
    四川省_南充市(Province.四川省, "13"),
    四川省_眉山市(Province.四川省, "14"),
    四川省_宜宾市(Province.四川省, "15"),
    四川省_广安市(Province.四川省, "16"),
    四川省_达州市(Province.四川省, "17"),
    四川省_雅安市(Province.四川省, "18"),
    四川省_巴中市(Province.四川省, "19"),
    四川省_资阳市(Province.四川省, "20"),
    四川省_阿坝藏族羌族自治州(Province.四川省, "32"),
    四川省_甘孜藏族自治州(Province.四川省, "33"),
    四川省_凉山彝族自治州(Province.四川省, "34"),

    贵州省_贵阳市(Province.贵州省, "01"),
    贵州省_六盘水市(Province.贵州省, "02"),
    贵州省_遵义市(Province.贵州省, "03"),
    贵州省_安顺市(Province.贵州省, "04"),
    贵州省_铜仁地区(Province.贵州省, "22"),
    贵州省_黔西南布依族苗族自治州(Province.贵州省, "23"),
    贵州省_毕节地区(Province.贵州省, "24"),
    贵州省_黔东南苗族侗族自治州(Province.贵州省, "26"),
    贵州省_黔南布依族苗族自治州(Province.贵州省, "27"),

    云南省_昆明市(Province.云南省, "01"),
    云南省_曲靖市(Province.云南省, "03"),
    云南省_玉溪市(Province.云南省, "04"),
    云南省_保山市(Province.云南省, "05"),
    云南省_昭通市(Province.云南省, "06"),
    云南省_丽江市(Province.云南省, "07"),
    云南省_普洱市(Province.云南省, "08"),
    云南省_临沧市(Province.云南省, "09"),
    云南省_楚雄彝族自治州(Province.云南省, "23"),
    云南省_红河哈尼族彝族自治州(Province.云南省, "25"),
    云南省_文山壮族苗族自治州(Province.云南省, "26"),
    云南省_西双版纳傣族自治州(Province.云南省, "28"),
    云南省_大理白族自治州(Province.云南省, "29"),
    云南省_德宏傣族景颇族自治州(Province.云南省, "31"),
    云南省_怒江傈僳族自治州(Province.云南省, "33"),
    云南省_迪庆藏族自治州(Province.云南省, "34"),

    西藏自治区_拉萨市(Province.西藏自治区, "01"),
    西藏自治区_昌都地区(Province.西藏自治区, "21"),
    西藏自治区_山南地区(Province.西藏自治区, "22"),
    西藏自治区_日喀则地区(Province.西藏自治区, "23"),
    西藏自治区_那曲地区(Province.西藏自治区, "24"),
    西藏自治区_阿里地区(Province.西藏自治区, "25"),
    西藏自治区_林芝地区(Province.西藏自治区, "26"),

    陕西省_西安市(Province.陕西省, "01"),
    陕西省_铜川市(Province.陕西省, "02"),
    陕西省_宝鸡市(Province.陕西省, "03"),
    陕西省_咸阳市(Province.陕西省, "04"),
    陕西省_渭南市(Province.陕西省, "05"),
    陕西省_延安市(Province.陕西省, "06"),
    陕西省_汉中市(Province.陕西省, "07"),
    陕西省_榆林市(Province.陕西省, "08"),
    陕西省_安康市(Province.陕西省, "09"),
    陕西省_商洛市(Province.陕西省, "10"),

    甘肃省_兰州市(Province.甘肃省, "01"),
    甘肃省_嘉峪关市(Province.甘肃省, "02"),
    甘肃省_金昌市(Province.甘肃省, "03"),
    甘肃省_白银市(Province.甘肃省, "04"),
    甘肃省_天水市(Province.甘肃省, "05"),
    甘肃省_武威市(Province.甘肃省, "06"),
    甘肃省_张掖市(Province.甘肃省, "07"),
    甘肃省_平凉市(Province.甘肃省, "08"),
    甘肃省_酒泉市(Province.甘肃省, "09"),
    甘肃省_庆阳市(Province.甘肃省, "10"),
    甘肃省_定西市(Province.甘肃省, "11"),
    甘肃省_陇南市(Province.甘肃省, "12"),
    甘肃省_临夏回族自治州(Province.甘肃省, "29"),
    甘肃省_甘南藏族自治州(Province.甘肃省, "30"),

    青海省_西宁市(Province.青海省, "01"),
    青海省_海东地区(Province.青海省, "21"),
    青海省_海北藏族自治州(Province.青海省, "22"),
    青海省_黄南藏族自治州(Province.青海省, "23"),
    青海省_海南藏族自治州(Province.青海省, "25"),
    青海省_果洛藏族自治州(Province.青海省, "26"),
    青海省_玉树藏族自治州(Province.青海省, "27"),
    青海省_海西蒙古族藏族自治州(Province.青海省, "28"),

    宁夏回族自治区_银川市(Province.宁夏回族自治区, "01"),
    宁夏回族自治区_石嘴山市(Province.宁夏回族自治区, "02"),
    宁夏回族自治区_吴忠市(Province.宁夏回族自治区, "03"),
    宁夏回族自治区_固原市(Province.宁夏回族自治区, "04"),
    宁夏回族自治区_中卫市(Province.宁夏回族自治区, "05"),

    新疆维吾尔自治区_乌鲁木齐市(Province.新疆维吾尔自治区, "01"),
    新疆维吾尔自治区_克拉玛依市(Province.新疆维吾尔自治区, "02"),
    新疆维吾尔自治区_吐鲁番地区(Province.新疆维吾尔自治区, "21"),
    新疆维吾尔自治区_哈密地区(Province.新疆维吾尔自治区, "22"),
    新疆维吾尔自治区_昌吉回族自治州(Province.新疆维吾尔自治区, "23"),
    新疆维吾尔自治区_博尔塔拉蒙古自治州(Province.新疆维吾尔自治区, "27"),
    新疆维吾尔自治区_巴音郭楞蒙古自治州(Province.新疆维吾尔自治区, "28"),
    新疆维吾尔自治区_阿克苏地区(Province.新疆维吾尔自治区, "29"),
    新疆维吾尔自治区_克孜勒苏柯尔克孜自治州(Province.新疆维吾尔自治区, "30"),
    新疆维吾尔自治区_喀什地区(Province.新疆维吾尔自治区, "31"),
    新疆维吾尔自治区_和田地区(Province.新疆维吾尔自治区, "32"),
    新疆维吾尔自治区_伊犁哈萨克自治州(Province.新疆维吾尔自治区, "40"),
    新疆维吾尔自治区_塔城地区(Province.新疆维吾尔自治区, "42"),
    新疆维吾尔自治区_阿勒泰地区(Province.新疆维吾尔自治区, "43"),

    台湾省_台湾省(Province.台湾省, "00"),
    香港特别行政区_香港特别行政区(Province.香港特别行政区, "00"),
    澳门特别行政区_澳门特别行政区(Province.澳门特别行政区, "00");

    private final String messageCode;
    private final Province province;

    private City(final Province province, final String messageCode) {
        this.province = province;
        this.messageCode = province.getMessageCode() + messageCode;
    }

    @Override
    public String getMessageCode() {
        return messageCode;
    }

    @Override
    public LookupType getMessageType() {
        return LookupType.CITY_CODE;
    }

    public Province getProvince() {
        return province;
    }
}
